algorithm: dfs

learning_rate: 0.00001
# --- data ---
num_samples:
  train: 10000
  val: 320
  test: 320

problem_size:
  train: 16
  val: 16
  test: 64


# --- model ---
num_node_states: 4
num_edge_states: 3

project: str = 'dnar_single_large_lr'
