algorithm: parallel_topological_sort
attention: 'entmax_sum'
# --- data ---
num_samples:
  train: 10000
  val: 320
  test: 320

problem_size:
  train: 16
  val: 16
  test: 64


num_node_states: 2
num_edge_states: 2

# Scalar output type for in-degree hints
output_type: scalar
output_idx: 0  # We output the in-degree scalar on self-loops
